### ISSUE TITLE
Fix custom fonts not being used in Android devices

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/jahir.dev#10]
| ![Screenshot_20211114-160040](https://user-images.githubusercontent.com/10360816/141698467-2c99aa82-a3ed-46d3-ab2a-5487923ac4bf.png) | ![IMG_4053](https://user-images.githubusercontent.com/10360816/141698474-71a523ab-0c90-4b21-bd91-22354b49dd30.PNG) |
|--------|--------|
| Android | iOS    |

**Comment by justinkruit** [comment]
I guess you mean the emojis? Because the font seems identical in the screenshots.

**Comment by jahirfiquitiva** [comment]
@justinkruit I actually mean the fonts. Give a close look to the titles, or the numbers ... you will see the differences 😅

**Comment by justinkruit** [comment]
> @justinkruit I actually mean the fonts. Give a close look to the titles, or the numbers ... you will see the differences 😅

You're correct, they look ever so different. Just compared the fonts of the iOS screenshot and on my own device, seems like I'm just seeing the "correct" one. 
![Screenshot_20220321-161724](https://user-images.githubusercontent.com/1642830/159292519-3669cc42-ca52-4666-8855-89fc77f43068.jpg)

**Comment by jahirfiquitiva** [comment]
@justinkruit interesting... not sure if it might be related to the device, android version or browser ... will give a deeper look later
thanks!

**Comment by jahirfiquitiva** [comment]
Fixed with newest website
