### ISSUE TITLE
Ops! JSONViewer link has a typo!

### ISSUE THREAD

**Issue by luigibarbato** [jahirfiquitiva/jahir.dev#37]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### URL

https://jahir.dev/uses

### Operating System

MacOS

### Browser

Chrome

### Browser Version

ndr

### What happened?

Hola! first of all, I wanted to congratulate you. you have done a superb job, I think it is one of the most beautiful I have seen lately. 

I simply wanted to point out this [typo](https://github.com/jahirfiquitiva/jahir.dev/blob/0d357af369a7485b2e140d46f71e4edd5062fd85/content/blog/uses.mdx?plain=1#L251), the link refers to the previous line. 

Bye! :)

### Reproduction Steps

JSON Viewer browser extension link on https://jahir.dev/uses page

**Comment by jahirfiquitiva** [comment]
It should be fixed now, thanks for the heads up! 😁
