### ISSUE TITLE
After Deployment on vercel, Styles are mess!!!!!

### ISSUE THREAD

**Issue by piyushyadav0191** [jahirfiquitiva/jahir.dev#44]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### URL

https://github.com/jahirfiquitiva/jahir.dev

### Operating System

Arch

### Browser

Chrome

### Browser Version

latest

### What happened?

On localhost, It is Looking fine but after deployment in vercel, styles are different and app is broken. I don't know how to solve it.

### Reproduction Steps

styles changed after deployment

### Screenshots or videos

![Screenshot_20230105_205259](https://user-images.githubusercontent.com/84402719/210815903-4562cb03-dd15-4c15-9000-e18489ce0b08.png)

**Comment by jahirfiquitiva** [comment]
Hi. This is made on purpose for you to make the styles your own. My website is not a template, but more of a project you can learn from.

**Comment by jahirfiquitiva** [comment]
@piyushyadav0191 I have added some information in the readme with details on how to "fix" that.
