### ISSUE TITLE
Broken link: "Edit on GItHub"

### ISSUE THREAD

**Issue by tszhong0411** [jahirfiquitiva/jahir.dev#64]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### URL

https://jahir.dev/blog/a-fresh-start

### Operating System

MacOS

### Browser

Chrome

### Browser Version

120.0.6099.129

### What happened?

The "Edit on GitHub" link is broken. It should point to `https://github.com/jahirfiquitiva/jahir.dev/edit/main/content/${slug}.mdx` instead.

https://github.com/jahirfiquitiva/jahir.dev/blob/d9a88d5686cff3eb0d541238f6a19db030670b62/src/app/blog/%5Bslug%5D/layout.tsx#L69C60-L69C60

### Reproduction Steps

Go to any posts on your blog. Click the "Edit on GitHub" link button.

### Expected behavior

Redirect to the correct mdx edit page.

**Comment by jahirfiquitiva** [comment]
🎉  Thanks for letting me know @tszhong0411 🙌
it should be fixed now 😁
