### ISSUE TITLE
Blog post link broken

### ISSUE THREAD

**Issue by JakeerC** [jahirfiquitiva/jahir.dev#84]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### URL

https://jahir.dev/blog/whats-in-my-raycast

### Operating System

Android

### Browser

Chrome

### Browser Version

100+

### What happened?

Blog post link broken

### Reproduction Steps

Open this link [whats-in-my-raycast](https://jahir.dev/blog/whats-in-my-raycast) in Android device chrome browser

**Comment by jahirfiquitiva** [comment]
Should be good now 🙌 Thanks for letting me know
